import type { LLMModelConfig } from './modelCatalog.ts';

const openAiBase = {
  provider: 'openrouter',
  logoKey: 'openai',
  fallbackProvider: 'openai',
} as const;

const anthropicBase = {
  provider: 'openrouter',
  logoKey: 'anthropic',
  fallbackProvider: 'anthropic',
} as const;

const geminiBase = {
  provider: 'openrouter',
  logoKey: 'gemini',
  fallbackProvider: 'google',
} as const;

const deepseekBase = {
  provider: 'openrouter',
  logoKey: 'deepseek',
} as const;

const openRouterBase = {
  provider: 'openrouter',
  logoKey: 'openrouter',
} as const;

const xaiOpenRouterBase = {
  provider: 'openrouter',
  logoKey: 'xai',
} as const;

const xaiDirectBase = {
  provider: 'xai',
  logoKey: 'xai',
  autoResumeOnIdle: false,
} as const;

const openAiModels = [
  {
    ...openAiBase,
    id: 'o3',
    apiModel: 'openai/o3',
    modelName: 'o3',
    shortName: 'o3',
    openRouterReasoningEnabled: true,
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'o4-mini',
    apiModel: 'openai/o4-mini',
    modelName: 'o4-mini',
    shortName: 'o4-mini',
    openRouterReasoningEnabled: true,
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'gpt-oss-120b',
    apiModel: 'openai/gpt-oss-120b',
    modelName: 'GPT-OSS 120B',
    shortName: 'GPT-OSS 120B',
    openRouterReasoningEnabled: true,
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'gpt-oss-120b-low',
    apiModel: 'openai/gpt-oss-120b',
    modelName: 'GPT-OSS 120B Low',
    shortName: 'GPT-OSS 120B L',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'low',
  },
  {
    ...openAiBase,
    id: 'gpt-oss-20b',
    apiModel: 'openai/gpt-oss-20b',
    modelName: 'GPT-OSS 20B',
    shortName: 'GPT-OSS 20B',
    openRouterReasoningEnabled: true,
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'gpt-oss-20b-low',
    apiModel: 'openai/gpt-oss-20b',
    modelName: 'GPT-OSS 20B Low',
    shortName: 'GPT-OSS 20B L',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'low',
  },
  {
    ...openAiBase,
    id: 'gpt-5-2-medium',
    apiModel: 'openai/gpt-5.2',
    modelName: 'GPT-5.2 Medium',
    shortName: 'GPT-5.2 M',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'medium',
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4',
    apiModel: 'openai/gpt-5.4',
    modelName: 'GPT-5.4',
    shortName: 'GPT-5.4',
    openRouterReasoningEnabled: true,
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4-non-reasoning',
    apiModel: 'openai/gpt-5.4',
    modelName: 'GPT-5.4 Non-Reasoning',
    shortName: 'GPT-5.4 NR',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4-mini-non-reasoning',
    apiModel: 'openai/gpt-5.4-mini',
    modelName: 'GPT-5.4 Mini Non-Reasoning',
    shortName: 'GPT-5.4 Mini NR',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4-mini-medium',
    apiModel: 'openai/gpt-5.4-mini',
    modelName: 'GPT-5.4 Mini Medium',
    shortName: 'GPT-5.4 Mini M',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'medium',
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4-mini-xhigh',
    apiModel: 'openai/gpt-5.4-mini',
    modelName: 'GPT-5.4 Mini XHigh',
    shortName: 'GPT-5.4 Mini XH',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'xhigh',
    openAiReasoningEffort: 'xhigh',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4-nano-non-reasoning',
    apiModel: 'openai/gpt-5.4-nano',
    modelName: 'GPT-5.4 Nano Non-Reasoning',
    shortName: 'GPT-5.4 Nano NR',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4-nano-medium',
    apiModel: 'openai/gpt-5.4-nano',
    modelName: 'GPT-5.4 Nano Medium',
    shortName: 'GPT-5.4 Nano M',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'medium',
    openAiReasoningEffort: 'medium',
  },
  {
    ...openAiBase,
    id: 'gpt-5-4-nano-xhigh',
    apiModel: 'openai/gpt-5.4-nano',
    modelName: 'GPT-5.4 Nano XHigh',
    shortName: 'GPT-5.4 Nano XH',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'xhigh',
    openAiReasoningEffort: 'xhigh',
  },
] as const satisfies readonly LLMModelConfig[];

const anthropicModels = [
  {
    ...anthropicBase,
    id: 'claude-4-5-haiku',
    apiModel: 'anthropic/claude-haiku-4.5',
    modelName: 'Claude Haiku 4.5',
    shortName: 'Haiku 4.5',
  },
  {
    ...anthropicBase,
    id: 'claude-4-5-haiku-reasoning',
    apiModel: 'anthropic/claude-haiku-4.5',
    modelName: 'Claude Haiku 4.5 Reasoning',
    shortName: 'Haiku 4.5 R',
    openRouterReasoningEnabled: true,
    anthropicThinking: {
      type: 'adaptive',
      display: 'summarized',
      effort: 'medium',
    },
  },
  {
    ...anthropicBase,
    id: 'claude-opus-4-6',
    apiModel: 'anthropic/claude-opus-4.6',
    modelName: 'Claude Opus 4.6',
    shortName: 'Opus 4.6',
    openRouterAssistantPrefillEnabled: false,
    openRouterReasoningEnabled: true,
    anthropicThinking: {
      type: 'adaptive',
      display: 'summarized',
      effort: 'high',
    },
  },
  {
    ...anthropicBase,
    id: 'claude-sonnet-4-6',
    apiModel: 'anthropic/claude-sonnet-4.6',
    modelName: 'Claude Sonnet 4.6',
    shortName: 'Sonnet 4.6',
    openRouterAssistantPrefillEnabled: false,
    openRouterReasoningEnabled: true,
    anthropicThinking: {
      type: 'adaptive',
      display: 'summarized',
      effort: 'high',
    },
  },
  {
    ...anthropicBase,
    id: 'claude-sonnet-4-6-non-reasoning-low-effort',
    apiModel: 'anthropic/claude-sonnet-4.6',
    modelName: 'Claude Sonnet 4.6 Low Effort',
    shortName: 'Sonnet 4.6 Low',
    openRouterAssistantPrefillEnabled: false,
  },
] as const satisfies readonly LLMModelConfig[];

const geminiModels = [
  {
    ...geminiBase,
    id: 'gemini-3-pro',
    apiModel: 'google/gemini-3-pro-preview',
    modelName: 'Gemini 3 Pro',
    shortName: 'Gemini 3 Pro',
    openRouterReasoningEnabled: true,
  },
  {
    ...geminiBase,
    id: 'gemini-3-pro-low',
    apiModel: 'google/gemini-3-pro-preview',
    modelName: 'Gemini 3 Pro Low',
    shortName: 'Gemini 3 Pro L',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'low',
  },
  {
    ...geminiBase,
    id: 'gemini-3-1-pro-preview',
    apiModel: 'google/gemini-3.1-pro-preview',
    modelName: 'Gemini 3.1 Pro Preview',
    shortName: 'Gemini 3.1 Pro',
    openRouterReasoningEnabled: true,
  },
  {
    ...geminiBase,
    id: 'gemini-3-1-pro-low-reasoning',
    apiModel: 'google/gemini-3.1-pro-preview',
    modelName: 'Gemini 3.1 Pro Low Reasoning',
    shortName: 'Gemini 3.1 Pro L',
    openRouterReasoningEnabled: true,
    openRouterReasoningEffort: 'low',
  },
  {
    ...geminiBase,
    id: 'gemini-3-1-flash-lite-preview',
    apiModel: 'google/gemini-3.1-flash-lite-preview',
    modelName: 'Gemini 3.1 Flash Lite Preview',
    shortName: 'Gemini 3.1 Flash Lite',
    openRouterReasoningEnabled: true,
  },
  {
    ...geminiBase,
    id: 'gemini-3-flash-reasoning',
    apiModel: 'google/gemini-3-flash-preview',
    modelName: 'Gemini 3 Flash Reasoning',
    shortName: 'Gemini 3 Flash R',
    openRouterReasoningEnabled: true,
  },
] as const satisfies readonly LLMModelConfig[];

const hermesModels = [
  {
    ...openRouterBase,
    id: 'hermes-4-llama-3-1-405b',
    apiModel: 'nousresearch/hermes-4-405b',
    modelName: 'Hermes 4 Llama 3.1 405B',
    shortName: 'Hermes 405B',
  },
  {
    ...openRouterBase,
    id: 'hermes-4-llama-3-1-405b-reasoning',
    apiModel: 'nousresearch/hermes-4-405b',
    modelName: 'Hermes 4 Llama 3.1 405B Reasoning',
    shortName: 'Hermes 405B R',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'hermes-4-llama-3-1-70b',
    apiModel: 'nousresearch/hermes-4-70b',
    modelName: 'Hermes 4 Llama 3.1 70B',
    shortName: 'Hermes 70B',
  },
  {
    ...openRouterBase,
    id: 'hermes-4-llama-3-1-70b-reasoning',
    apiModel: 'nousresearch/hermes-4-70b',
    modelName: 'Hermes 4 Llama 3.1 70B Reasoning',
    shortName: 'Hermes 70B R',
    openRouterReasoningEnabled: true,
  },
] as const satisfies readonly LLMModelConfig[];

const ministralModels = [
  {
    ...openRouterBase,
    id: 'ministral-3-14b',
    apiModel: 'mistralai/ministral-14b-2512',
    modelName: 'Ministral 3 14B',
    shortName: 'Ministral 3 14B',
  },
  {
    ...openRouterBase,
    id: 'ministral-3-3b',
    apiModel: 'mistralai/ministral-3b-2512',
    modelName: 'Ministral 3 3B',
    shortName: 'Ministral 3 3B',
  },
  {
    ...openRouterBase,
    id: 'ministral-3-8b',
    apiModel: 'mistralai/ministral-8b-2512',
    modelName: 'Ministral 3 8B',
    shortName: 'Ministral 3 8B',
  },
] as const satisfies readonly LLMModelConfig[];

const xaiDirectModels = [
  {
    ...xaiDirectBase,
    id: 'grok-4-1-fast',
    apiModel: 'grok-4-1-fast-non-reasoning',
    modelName: 'Grok 4.1 Fast',
    shortName: 'Grok 4.1 Fast',
  },
  {
    ...xaiDirectBase,
    id: 'grok-4-1-fast-reasoning',
    apiModel: 'grok-4-1-fast-reasoning',
    modelName: 'Grok 4.1 Fast Reasoning',
    shortName: 'Grok 4.1 Fast R',
  },
  {
    ...xaiDirectBase,
    id: 'grok-code-fast-1',
    apiModel: 'grok-code-fast-1',
    modelName: 'Grok Code Fast 1',
    shortName: 'Grok Code Fast 1',
  },
] as const satisfies readonly LLMModelConfig[];

const xaiOpenRouterModels = [
  {
    ...xaiOpenRouterBase,
    id: 'grok-4-20',
    apiModel: 'x-ai/grok-4.20-beta',
    modelName: 'Grok 4.20',
    shortName: 'Grok 4.20',
    openRouterReasoningEnabled: true,
  },
  {
    ...xaiOpenRouterBase,
    id: 'grok-4-20-non-reasoning',
    apiModel: 'x-ai/grok-4.20-beta',
    modelName: 'Grok 4.20 Non-Reasoning',
    shortName: 'Grok 4.20 NR',
  },
] as const satisfies readonly LLMModelConfig[];

const deepseekModels = [
  {
    ...deepseekBase,
    id: 'deepseek-r1-0120',
    apiModel: 'deepseek/deepseek-r1',
    modelName: 'DeepSeek R1 0120',
    shortName: 'DeepSeek R1 0120',
    openRouterReasoningEnabled: true,
  },
] as const satisfies readonly LLMModelConfig[];

const otherOpenRouterModels = [
  {
    ...openRouterBase,
    id: 'kimi-k2',
    apiModel: 'moonshotai/kimi-k2',
    modelName: 'Kimi K2',
    shortName: 'Kimi K2',
  },
  {
    ...openRouterBase,
    id: 'kimi-k2-0905',
    apiModel: 'moonshotai/kimi-k2-0905',
    modelName: 'Kimi K2 0905',
    shortName: 'Kimi K2 0905',
  },
  {
    ...openRouterBase,
    id: 'kimi-k2-5',
    apiModel: 'moonshotai/kimi-k2.5',
    modelName: 'Kimi K2.5',
    shortName: 'Kimi K2.5',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'kimi-k2-5-non-reasoning',
    apiModel: 'moonshotai/kimi-k2.5',
    modelName: 'Kimi K2.5 Non-Reasoning',
    shortName: 'Kimi K2.5 NR',
  },
  {
    ...openRouterBase,
    id: 'intellect-3',
    apiModel: 'prime-intellect/intellect-3',
    modelName: 'INTELLECT-3',
    shortName: 'INTELLECT-3',
  },
  {
    ...openRouterBase,
    id: 'mercury-2',
    apiModel: 'inception/mercury-2',
    modelName: 'Mercury 2',
    shortName: 'Mercury 2',
  },
  {
    ...openRouterBase,
    id: 'longcat-flash-lite',
    apiModel: 'meituan/longcat-flash-chat',
    modelName: 'LongCat Flash Lite',
    shortName: 'LongCat Flash Lite',
  },
  {
    ...openRouterBase,
    id: 'step-3-5-flash',
    apiModel: 'stepfun/step-3.5-flash',
    modelName: 'Step 3.5 Flash',
    shortName: 'Step 3.5 Flash',
  },
  {
    ...openRouterBase,
    id: 'olmo-3-1-32b-instruct',
    apiModel: 'allenai/olmo-3.1-32b-instruct',
    modelName: 'Olmo 3.1 32B Instruct',
    shortName: 'Olmo 3.1 32B',
  },
  {
    ...openRouterBase,
    id: 'lfm2-24b-a2b',
    apiModel: 'liquid/lfm-2-24b-a2b',
    modelName: 'LFM2 24B A2B',
    shortName: 'LFM2 24B',
  },
  {
    ...openRouterBase,
    id: 'mistral-small-4',
    apiModel: 'mistralai/mistral-small-2603',
    modelName: 'Mistral Small 4',
    shortName: 'Mistral Small 4',
  },
  {
    ...openRouterBase,
    id: 'mistral-small-4-non-reasoning',
    apiModel: 'mistralai/mistral-small-2603',
    modelName: 'Mistral Small 4 Non-Reasoning',
    shortName: 'Mistral Small 4 NR',
  },
  {
    ...openRouterBase,
    id: 'minimax-m2-7',
    apiModel: 'minimax/minimax-m2.7',
    modelName: 'MiniMax M2.7',
    shortName: 'MiniMax M2.7',
  },
  {
    ...openRouterBase,
    id: 'nvidia-nemotron-3-super-120b-a12b',
    apiModel: 'nvidia/nemotron-3-super-120b-a12b',
    modelName: 'Nemotron 3 Super 120B A12B',
    shortName: 'Nemotron 3 Super',
  },
  {
    ...openRouterBase,
    id: 'nvidia-nemotron-3-nano-30b-a3b',
    apiModel: 'nvidia/nemotron-3-nano-30b-a3b',
    modelName: 'Nemotron 3 Nano 30B A3B',
    shortName: 'Nemotron 3 Nano',
  },
  {
    ...openRouterBase,
    id: 'nvidia-nemotron-3-nano-30b-a3b-reasoning',
    apiModel: 'nvidia/nemotron-3-nano-30b-a3b',
    modelName: 'Nemotron 3 Nano 30B A3B Reasoning',
    shortName: 'Nemotron 3 Nano R',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-max-thinking',
    apiModel: 'qwen/qwen3-max-thinking',
    modelName: 'Qwen3 Max Thinking',
    shortName: 'Qwen3 Max Thinking',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-0-8b',
    apiModel: 'qwen/qwen3-0.6b-04-28',
    modelName: 'Qwen3.5 0.8B',
    shortName: 'Qwen3.5 0.8B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-0-8b-non-reasoning',
    apiModel: 'qwen/qwen3-0.6b-04-28',
    modelName: 'Qwen3.5 0.8B Non-Reasoning',
    shortName: 'Qwen3.5 0.8B NR',
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-2b',
    apiModel: 'qwen/qwen3-1.7b',
    modelName: 'Qwen3.5 2B',
    shortName: 'Qwen3.5 2B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-2b-non-reasoning',
    apiModel: 'qwen/qwen3-1.7b',
    modelName: 'Qwen3.5 2B Non-Reasoning',
    shortName: 'Qwen3.5 2B NR',
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-4b',
    apiModel: 'qwen/qwen3-4b',
    modelName: 'Qwen3.5 4B',
    shortName: 'Qwen3.5 4B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-4b-non-reasoning',
    apiModel: 'qwen/qwen3-4b',
    modelName: 'Qwen3.5 4B Non-Reasoning',
    shortName: 'Qwen3.5 4B NR',
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-9b',
    apiModel: 'qwen/qwen3.5-9b',
    modelName: 'Qwen3.5 9B',
    shortName: 'Qwen3.5 9B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-9b-non-reasoning',
    apiModel: 'qwen/qwen3.5-9b',
    modelName: 'Qwen3.5 9B Non-Reasoning',
    shortName: 'Qwen3.5 9B NR',
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-27b',
    apiModel: 'qwen/qwen3.5-27b',
    modelName: 'Qwen3.5 27B',
    shortName: 'Qwen3.5 27B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-27b-non-reasoning',
    apiModel: 'qwen/qwen3.5-27b',
    modelName: 'Qwen3.5 27B Non-Reasoning',
    shortName: 'Qwen3.5 27B NR',
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-35b-a3b',
    apiModel: 'qwen/qwen3.5-35b-a3b',
    modelName: 'Qwen3.5 35B A3B',
    shortName: 'Qwen3.5 35B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-35b-a3b-non-reasoning',
    apiModel: 'qwen/qwen3.5-35b-a3b',
    modelName: 'Qwen3.5 35B A3B Non-Reasoning',
    shortName: 'Qwen3.5 35B NR',
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-122b-a10b',
    apiModel: 'qwen/qwen3.5-122b-a10b',
    modelName: 'Qwen3.5 122B A10B',
    shortName: 'Qwen3.5 122B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-122b-a10b-non-reasoning',
    apiModel: 'qwen/qwen3.5-122b-a10b',
    modelName: 'Qwen3.5 122B A10B Non-Reasoning',
    shortName: 'Qwen3.5 122B NR',
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-397b-a17b',
    apiModel: 'qwen/qwen3.5-397b-a17b',
    modelName: 'Qwen3.5 397B A17B',
    shortName: 'Qwen3.5 397B',
    openRouterReasoningEnabled: true,
  },
  {
    ...openRouterBase,
    id: 'qwen3-5-397b-a17b-non-reasoning',
    apiModel: 'qwen/qwen3.5-397b-a17b',
    modelName: 'Qwen3.5 397B A17B Non-Reasoning',
    shortName: 'Qwen3.5 397B NR',
  },
  {
    ...openRouterBase,
    id: 'glm-5-non-reasoning',
    apiModel: 'z-ai/glm-5',
    modelName: 'GLM-5 Non-Reasoning',
    shortName: 'GLM-5 NR',
  },
] as const satisfies readonly LLMModelConfig[];

export const additionalModelCatalog = [
  ...openAiModels,
  ...anthropicModels,
  ...geminiModels,
  ...hermesModels,
  ...ministralModels,
  ...xaiDirectModels,
  ...xaiOpenRouterModels,
  ...deepseekModels,
  ...otherOpenRouterModels,
] as const satisfies readonly LLMModelConfig[];
